[package]
name = "regression-test-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
regression-test = { path = "../regression-test" }
syn = { version = "2.0.104", features = ["full"] }
