[package]
name = "example-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
regression-test = { path = "../regression-test" }
regression-test-macros = { path = "../regression-test-macros" }
